on:
  push:
    paths:
      - .github/workflows/build.yml
      - src/**
      - include/**
      - xmake.lua
  pull_request:
  workflow_dispatch:

jobs:
  build-windows:
    name: Build on Windows (MSVC)
    runs-on: windows-2022
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup MSVC
      uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: x64
        
    - name: Install xmake
      uses: xmake-io/github-action-setup-xmake@v1
        
    - name: Build NBT Static (Debug)
      run: xmake config --mode=debug --kind=static -y && xmake --all -y

    - name: Build NBT Shared (Debug)
      run: xmake config --mode=debug --kind=shared -y && xmake --all -y
      
    - name: Build NBT Static (Release)
      run: xmake config --mode=release --kind=static -y && xmake --all -y

    - name: Build NBT Shared (Release)
      run: xmake config --mode=release --kind=shared -y && xmake --all -y

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: NBT-windows-x86_64-${{ github.sha }}
        path: |
          bin/

  build-linux:
    name: Build on Linux (Clang)
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup Clang
      run: |
        sudo apt-get update && sudo apt-get install -y clang
        sudo apt-get update
        sudo apt-get install -y clang libc++-dev libc++abi-dev
      
    - name: Install xmake
      uses: xmake-io/github-action-setup-xmake@v1
        
    - name: Build NBT Static (Debug)
      run: xmake config --mode=debug --kind=static -y && xmake --all -y

    - name: Build NBT Shared (Debug)
      run: xmake config --mode=debug --kind=shared -y && xmake --all -y
      
    - name: Build NBT Static (Release)
      run: xmake config --mode=release --kind=static -y && xmake --all -y

    - name: Build NBT Shared (Release)
      run: xmake config --mode=release --kind=shared -y && xmake --all -y

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: NBT-linux-x86_64-${{ github.sha }}
        path: |
          bin/